### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ghost** [qmegas/di-fm-ad-blocker#5]
Hello! 
I'm completely new to github and i have no idea how to use this script. I would be greatful if somebody could explain it to me or give me some useful video tutorial link. You say that all i need to do is download the extension but you don't give any links. There is only code and i don't know what to do with it. I would be really greatful for some help :)

**Comment by qmegas** [comment]
Install `Tampermonkey` extension in your browser, then manually add a content of `difm.user.js` file or just [click here](http://qmegas.info/js/difm.user.js)
